#
# Aliases
#

alias gfl='git flow'
alias gfli='git flow init'
alias gflc='git flow config'
alias gfll='git flow log'
alias gflv='git flow version'

alias gflf='git flow feature'
alias gflfl='git flow feature list'
alias gflfs='git flow feature start'
alias gflff='git flow feature finish --no-ff'
alias gflfp='git flow feature publish'
alias gflft='git flow feature track'
alias gflfd='git flow feature diff'
alias gflfr='git flow feature rebase'
alias gflfc='git flow feature checkout'
alias gflfm='git flow feature pull'
alias gflfx='git flow feature delete'

alias gflb='git flow bugfix'
alias gflbl='git flow bugfix list'
alias gflbs='git flow bugfix start'
alias gflbf='git flow bugfix finish --no-ff'
alias gflbp='git flow bugfix publish'
alias gflbt='git flow bugfix track'
alias gflbd='git flow bugfix diff'
alias gflbr='git flow bugfix rebase'
alias gflbc='git flow bugfix checkout'
alias gflbm='git flow bugfix pull'
alias gflbx='git flow bugfix delete'

alias gflr='git flow release'
alias gflrl='git flow release list'
alias gflrs='git flow release start'
alias gflrf='git flow release finish'
alias gflrp='git flow release publish'
alias gflrt='git flow release track'
alias gflrd='git flow release diff'
alias gflrr='git flow release rebase'
alias gflrc='git flow release checkout'
alias gflrm='git flow release pull'
alias gflrx='git flow release delete'

alias gflh='git flow hotfix'
alias gflhl='git flow hotfix list'
alias gflhs='git flow hotfix start'
alias gflhf='git flow hotfix finish'
alias gflhp='git flow hotfix publish'
alias gflht='git flow hotfix track'
alias gflhd='git flow hotfix diff'
alias gflhr='git flow hotfix rebase'
alias gflhc='git flow hotfix checkout'
alias gflhm='git flow hotfix pull'
alias gflhx='git flow hotfix delete'

alias gfls='git flow support'
alias gflsl='git flow support list'
alias gflss='git flow support start'
alias gflsf='git flow support finish'
alias gflsp='git flow support publish'
alias gflst='git flow support track'
alias gflsd='git flow support diff'
alias gflsr='git flow support rebase'
alias gflsc='git flow support checkout'
alias gflsm='git flow support pull'
alias gflsx='git flow support delete'
