#
# Aliases
#

alias gfl='git flow'
alias gfli='git flow init'
alias gfll='git flow log'
alias gflv='git flow version'

alias gflc='git flow config'
alias gflcs='git flow config set'
alias gflcb='git flow config base'

alias gflf='git flow feature'
alias gflfl='git flow feature list'
alias gflfs='git flow feature start'
alias gflff='git flow feature finish --no-ff'
alias gflff!='git flow feature finish --no-ff --force'
alias gflfp='git flow feature publish'
alias gflft='git flow feature track'
alias gflfd='git flow feature diff'
alias gflfr='git flow feature rebase'
alias gflfc='git flow feature checkout'
alias gflfc!='git flow feature checkout --force'
alias gflfm='git flow feature pull'
alias gflfm!='git flow feature pull --force'
alias gflfx='git flow feature delete'
alias gflfx!='git flow feature delete --force'
alias gflfn='git flow feature rename'
alias gflfh='git flow feature help'

alias gflb='git flow bugfix'
alias gflbl='git flow bugfix list'
alias gflbs='git flow bugfix start'
alias gflbf='git flow bugfix finish --no-ff'
alias gflbf!='git flow bugfix finish --no-ff  --force'
alias gflbp='git flow bugfix publish'
alias gflbt='git flow bugfix track'
alias gflbd='git flow bugfix diff'
alias gflbr='git flow bugfix rebase'
alias gflbc='git flow bugfix checkout'
alias gflbm='git flow bugfix pull'
alias gflbx='git flow bugfix delete'
alias gflbx!='git flow bugfix delete --force'
alias gflbn='git flow bugfix rename'
alias gflbh='git flow bugfix help'

alias gflr='git flow release'
alias gflrl='git flow release list'
alias gflrs='git flow release start'
alias gflrf='git flow release finish'
alias gflrb='git flow release branch'
alias gflrp='git flow release publish'
alias gflrt='git flow release track'
alias gflrx='git flow release delete'
alias gflrx!='git flow release delete  --force'
alias gflrr='git flow release rebase'
alias gflrh='git flow release help'

alias gflh='git flow hotfix'
alias gflhl='git flow hotfix list'
alias gflhs='git flow hotfix start'
alias gflhf='git flow hotfix finish'
alias gflhp='git flow hotfix publish'
alias gflhx='git flow hotfix delete'
alias gflhx!='git flow hotfix delete --force'
alias gflhr='git flow hotfix rebase'
alias gflhn='git flow hotfix rename'
alias gflhh='git flow hotfix help'

alias gfls='git flow support'
alias gflsl='git flow support list'
alias gflss='git flow support start'
alias gflsr='git flow support rebase'
alias gflsh='git flow support help'
